### ISSUE TITLE
Standalone pages

### ISSUE THREAD

**Issue by salazar** [shenoybr/hugo-goa#11]
Hey, the suggested way of creating standalone pages doesn't seem to be working -- at least in my installation of hugo. The "About" page, for instance, shows no content.

![2016-12-02-032107_859x370_scrot](https://cloud.githubusercontent.com/assets/2211720/20823783/7407be5a-b83e-11e6-810d-17204cc17f3a.png)

**Comment by shenoybr** [comment]
It looks like your about page is using the list template. What is the directory structure you are using?

**Comment by salazar** [comment]
Forgot to mention -- sorry -- that I was just checking out https://github.com/shenoybr/hugo-goa-demo

**Comment by shenoybr** [comment]
What version of hugo are you using?

**Comment by salazar** [comment]
> What version of hugo are you using?

$ hugo version
Hugo Static Site Generator v0.18-DEV BuildDate: 2016-12-02T00:44:45-02:00


- Salazar

**Comment by salazar** [comment]
Let me try it with 0.17; sec.

**Comment by salazar** [comment]
It does work with 0.17.

**Comment by shenoybr** [comment]
ok, so its some sort of breaking change in 0.18 I guess.

**Comment by shenoybr** [comment]
You are very welcome :)

**Comment by sadmansk** [comment]
i'm having this same issue, hope it gets fixed soon, thanks for building this really nice theme though!

**Comment by salazar** [comment]
@sadmansk, last I tried it worked with Hugo 0.17. You can downgrade until there's a fix :)
