### ISSUE TITLE
Error when set baseurl

### ISSUE THREAD

**Issue by simon-xia** [shenoybr/hugo-goa#14]
when set baseurl to `https://localhost/`, the layout of main page seems error, in my computer, I got the exampleSite like this

<img width="1440" alt="screen shot 2017-02-01 at 12 53 01 am" src="https://cloud.githubusercontent.com/assets/6264665/22475081/d4c28022-e818-11e6-8a4e-3cdccddce1b3.png">

**Comment by shenoybr** [comment]
It is probably looking for the css files, which don't happen to be available at that URL. could you check if your site is actually at localhost?

**Comment by simon-xia** [comment]
yep, site is running on that baseurl

```
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
5 regular pages created
19 other pages created
0 non-page files copied
0 paginator pages created
9 tags created
4 categories created
total in 19 ms
Watching for changes in /Users/simon/exampleSite/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by shenoybr** [comment]
your server is available at http://localhost:1313/ and not localhost... could you try that?

**Comment by shenoybr** [comment]
Also, you seem to be using https... not sure if that works locally.

**Comment by simon-xia** [comment]
it still not work for me. Have you try it with `exampleSite`? Is that correct ?

**Comment by ccorpmx** [comment]
@simon-xia try to set your `baseURL = "http://localhost/"`

**Comment by jashk** [comment]
@simon-xia try to set your `baseURL = "http://localhost/"`

**Comment by shenoybr** [comment]
I think his baseURL should be set as follows: `baseURL = http://localhost:1313`. Regardless, he could try either suggestion and see if it works.

**Comment by utkarshshah007** [comment]
@shenoybr I'm seeing this too... seems like it will work with

`baseURL = http://something.com/anything`

but not with

`baseURL = http://something.com/`

**Comment by shenoybr** [comment]
I can't reproduce this
```
$ hugo server -w -v
INFO: 2017/10/09 20:42:46 hugo.go:463: Using config file: /Users/shenoybr/dev/hugo-goa-demo/config.toml
INFO: 2017/10/09 20:42:46 hugo.go:575: using a UnionFS for static directory comprised of:
INFO: 2017/10/09 20:42:46 hugo.go:576: Base: /Users/shenoybr/dev/hugo-goa-demo/themes/hugo-goa/static
INFO: 2017/10/09 20:42:46 hugo.go:577: Overlay: /Users/shenoybr/dev/hugo-goa-demo/static/
INFO: 2017/10/09 20:42:46 hugo.go:609: syncing static files to /
Started building site
INFO: 2017/10/09 20:42:46 site.go:1251: found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
0 draft content
0 future content
5 pages created
0 non-page files copied
0 paginator pages created
9 tags created
4 categories created
in 87 ms
Watching for changes in /Users/shenoybr/dev/hugo-goa-demo/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```
Using baseurl="`https://shenoybr.github.io/`"
