### ISSUE TITLE
[Not Loaded] index.html in /about/

### ISSUE THREAD

**Issue by Hitaro** [shenoybr/hugo-goa#15]
`index.html` in `/content/about` folder is not loaded at: http://localhost:1313/about, look at the below page, plz:

![spectacle h16556](https://cloud.githubusercontent.com/assets/18015032/23078200/ea47f2d2-f55c-11e6-8216-9a5a5ad84f5b.png)

But if I change the file name to something else like `test.md`, it's loaded at http://localhost:1313/about/test

Also, if I rename `/content/about/index.md` file to `about.md` and move it to the `/content`, it will be loaded at http://localhost:1313/about currectly.

There's same issue with the 3rd item in the main menu.

    ## Main Menu
    [[menu.main]]
        name = "blog"
        weight = 100
        identifier = "blog"
        url = "/blog/"
    [[menu.main]]
        name = "about"
        identifier = "about"
        weight = 200
        url = "/about/"
    [[menu.main]]
        name = "3rd"
        identifier = "3rd"
        weight = 300
        url = "/3rd/"

**Comment by aristote** [comment]
I have the same "bug". Seems it was "brought" by the latest hugo version.

**Comment by aristote** [comment]
Ok. "Fixed" the "bug" (it's a Hugo 0.18 feature). move your /content/about/index.md to /content/about.md and regenerate your site. It should create a /about/index.html

**Comment by mathcass** [comment]
I can confirm the same issue as well as @aristote's fix. If that's the case and this is new functionality, it might make sense to update the instructions for the latest version of Hugo.

**Comment by pandeazucar** [comment]
I started building my blog with @aristote fix and it works, it renders index.html, the only problem though is that now my single pages have an undesired control button (either next or previous).

![hugo_goa_bug](https://user-images.githubusercontent.com/3105757/27172498-1b30dca4-517b-11e7-87a0-088d728f2736.png)

The single pages should not have this button.

**Comment by shenoybr** [comment]
This seems to be working. I generated a new version of the site and the menu's work as expected https://shenoybr.github.io/hugo-goa-demo/about/

**Comment by shenoybr** [comment]
I discovered that this can happen if you provide an alternate 'slug'. Removing that makes this issue go away. Slug should be empty for pages.
