### ISSUE TITLE
Disqus not working

### ISSUE THREAD

**Issue by LukasMa** [shenoybr/hugo-goa#2]
I'm a hugo newbie, but it seems that disqus doesn't work. I added my shortname, but don't see any comment section. I also can't find a reference to the internal disqus template in your repo.

**Comment by shenoybr** [comment]
This has now been fixed. You can use this setting to control which pages show comments:
https://github.com/shenoybr/hugo-goa#page-settings

**Comment by shenoybr** [comment]
[Here](https://shenoybr.github.io/hugo-goa-demo/blog/first/) is the demo site that uses this setting.
