### ISSUE TITLE
Avatar image url doesn't honor baseURL

### ISSUE THREAD

**Issue by davidcai** [shenoybr/hugo-goa#26]
I have the following setting in config.toml:

```
baseurl = "https://davidcai.github.io/dcai-blog"
canonifyURLs = true
```

All images in blog posts have correct base URLs prefixed to image filenames, e.g. "https://davidcai.github.io/dcai-blog/img/snapshot-diff.png". However, for the avatar/author image, the src attribute still points to "img/headshot.jpg" which doesn't include path "dcai-blog".

I guess the problem is in `layouts/partials/avatar.html`:

```html
{{ with .Site.Params.authorimage }} <img src="img/{{ . }}" alt="Author Image" class="img-circle text-center headshot"> {{ end }}
```

If I put `/` in front of `img/{{ . }}`, the image URL will be correctly resolved as "https://davidcai.github.io/dcai-blog/img/headshot.jpg".

**Comment by shenoybr** [comment]
@davidcai could you submit a PR for this?

**Comment by davidcai** [comment]
@shenoybr Sure. Here is the PR: https://github.com/shenoybr/hugo-goa/pull/31

**Comment by shenoybr** [comment]
@davidcai merged
