### ISSUE TITLE
Post appearing in reverse chronological order 

### ISSUE THREAD

**Issue by mattkcole** [shenoybr/hugo-goa#28]
For some reason, I believe right after I installed the latest hugo-goa theme, my posts started appearing in reverse order. Is this a known issue? The theme is really great and I would love to continue to use it  😄 

hugo version: 0.30

**Comment by shenoybr** [comment]
@mattkcole I am not sure. Maybe something in config? https://shenoybr.github.io/hugo-goa-demo/blog/

**Comment by viraj071** [comment]
I am facing the same problem. Anyone find a solution yet?

**Comment by NicholasJacques** [comment]
I am having the same issue.

**Comment by NicholasJacques** [comment]
I just noticed that the order is only wrong when viewing my site locally. When deployed to production my blog posts are listed in the correct (descending) order. Adding `.Reverse` to the li.html partial fixes my site locally but makes the ordering incorrect in production. Weird.

**Comment by joedborg** [comment]
Just notices exactly the same, it appears to be a new bug (or I've not spotted it before).

**Comment by medakk** [comment]
I have the same problem. Posts are arranged in descending order locally, but ascending in production.
