### ISSUE TITLE
Enable picture in the blog article

### ISSUE THREAD

**Issue by Heceo** [shenoybr/hugo-goa#58]
Hello!

This is a concise and wonderful theme for blogs, but I'm wondering where to enable showing pictures in the articles of blog. It seems that the function isn't supported. But I don't think a blog is complete without pictures. I really appreciate it if you tell me how to do.

**Comment by pineapplegiant** [comment]
I've also had this problem. So far I've been just adding the raw html as a temporary hack. Sometimes I'll wrap it in a center tag width some styling or sizing.

`<center><img height="400" width: "400"src="/img/image.jpg></center>`

Although the more pleasing markdown way would be nice:

`![My hip image](/img/image.jpg)`

I haven't really looked into a solution though, but I don't think it should be too bad...

**Comment by gmagno** [comment]
Hugo's Figure shortcode works fine for me:

    {{< figure src="/img/fig.jpg"
        title="Some title"
        width="300"
    >}}

I hope it helps.
More info here: [Hugo's Figure shortcode](https://gohugo.io/content-management/shortcodes/#figure)
