### ISSUE TITLE
How do I update my local fork with current version in original?

### ISSUE THREAD

**Issue by timbmg** [shenoybr/hugo-goa#65]
...without losing my configuration and content?

**Comment by rhamzeh** [comment]
You've done changes to the theme itself? Configuration changes to your site shouldn't be affected by this.

The theme usually is under `themes/hugo-goa` in your base hugo folder and is not usually modified.

If you go to that directory on the terminal, and type `git status` what do you see?

If there are no changes, do a `git log` and make a note the last working revision you were on (in case any of the new changes mess with your site). After that a simple `git pull` should suffice. Rebuild your site and make sure everything is working as you expect before you redeploy it. 

** Note, just for peace of mind you might want to take a backup of the whole folder before doing all this.
