### ISSUE TITLE
How do I disable to  insert Table of Contents automatically

### ISSUE THREAD

**Issue by owlinux1000** [shenoybr/hugo-goa#75]
The problem article and git repository of its is here. Sorry written in Japanese. But it is no matter.
https://alicemacs.com/blog/predict_lcg/
https://github.com/owlinux1000/blog

I don't want to insert Table of Contents. But, This is automatically inserted. How do I disable it.

**Comment by connor11528** [comment]
@owlinux1000 you can set `toc = false` in your config.toml file

**Comment by jsigee87** [comment]
@connor11528  do you have any more insight here? Having the same issue where an auto-generated TOC is being generated, but is rendered incorrectly and so I would like to disable it. Adding `toc = false` to the config.toml did not resolve it.

**Comment by connor11528** [comment]
@jsigee87 put `toc: false` in your blog post too. Here's an example file: https://raw.githubusercontent.com/connor11528/connorleech.info/master/content/blog/2-Types-of-Software-Engineering-Interviews.md

**Comment by jsigee87** [comment]
Awesome that was what I was missing. Thanks!

**Comment by owlinux1000** [comment]
@connor11528  Thanks a lot!! I resolved this issue!
