### ISSUE TITLE
New Google Analytics snippet

### ISSUE THREAD

**Issue by chrish42** [shenoybr/hugo-goa#94]
Google has a new recommended Google Analytics snippet to replace the current one used by the theme:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=INSERT_GA_ID_HERE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', INSERT_GA_ID_HERE);
</script>
```

**Comment by xaner4** [comment]
The theme itself does not manage the google analytics snippets as it uses a internal template snippet generated by hugo, however there is a PR over on the Hugo repo that have added the new snippet https://github.com/gohugoio/hugo/pull/7780

**Comment by chrish42** [comment]
Oh. I didn't catch this detail, apparently. And thanks for the link to the Hugo issue. We can close this bug, then. Thanks again!
